version: "0.0.3-{build}"
environment:
  global:
    LOCC_VERSION: "0.0.3"
  matrix:
    - job_name: Windows x64
      appveyor_build_worker_image: Visual Studio 2019
    - job_name: Linux x64
      appveyor_build_worker_image: Ubuntu
configuration:
  - Release
install:
  - cmd: cmake -G "Visual Studio 16 2019" .
  - sh: cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=$CONFIGURATION .
for:
  - matrix:
      only:
        - job_name: Windows x64
    build:
      project: locc.sln
      parallel: true
      verbosity: minimal
    artifacts:
      - path: locc-v0.0.3-Windows-x64.zip
  - matrix:
      only:
        - job_name: Linux x64
    build_script:
      - sh: echo -e "Version=$LOCC_VERSION\n == Building Linux $CONFIGURATION ==" && ninja -v || exit 1
    artifacts:
      - path: locc-v0.0.3-Linux-x64.tar.gz
test_script:
  - cmd: |
      .\Release\locc.exe -dbv . || exit 1
      .\Release\locc.exe --version || exit 1
  - sh: ./locc -dbv . || exit 1; ./locc --version || exit 1
after_build:
  - cmd: 7z a locc-v0.0.3-Windows-x64.zip %APPVEYOR_BUILD_FOLDER%\Release\locc.exe
  - sh: tar -caf locc-v0.0.3-Linux-x64.tar.gz locc
deploy:
  - provider: GitHub
    tag: "v0.0.3"
    release: "locc-v0.0.3"
    description: "Instigator: Appveyor CI script"
    auth_token:
      secure: Q4k4QeaxqXS7TIPI+dKfG8m2a8RTpP9G4sbpxhA9isKu3PgZywKwy5+ecPXyS7A5
    artifact: locc-v0.0.3-Windows-x64.zip,locc-v0.0.3-Linux-x64.tar.gz
    draft: true
    prerelease: true
    on:
      APPVEYOR_REPO_TAG: true

matrix:
  fast_finish: true

skip_branch_with_pr: true
